set_property IOSTANDARD LVCMOS18 [get_ports SPI0_SCLK_O]
set_property IOSTANDARD LVCMOS18 [get_ports SPI0_SS_O]
set_property IOSTANDARD LVCMOS18 [get_ports SPI0_MOSI_O]

set_property IOSTANDARD LVCMOS18 [get_ports SPI0_SS1_O]
set_property IOSTANDARD LVCMOS18 [get_ports SPI0_SS2_O]

set_property IOSTANDARD LVCMOS18 [get_ports {gpio_io_o[0]}]
set_property PACKAGE_PIN K15 [get_ports {gpio_io_o[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports clk_adc]
set_property IOSTANDARD LVCMOS18 [get_ports I_b0_b1]
set_property IOSTANDARD LVCMOS18 [get_ports I_b2_b3]
set_property IOSTANDARD LVCMOS18 [get_ports I_b4_b5]
set_property IOSTANDARD LVCMOS18 [get_ports I_b6_b7]
set_property IOSTANDARD LVCMOS18 [get_ports I_b8_b9]
set_property IOSTANDARD LVCMOS18 [get_ports I_b10_b11]
set_property IOSTANDARD LVCMOS18 [get_ports I_b12_b13]
set_property IOSTANDARD LVCMOS18 [get_ports I_b14_b15]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b0_b1]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b2_b3]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b4_b5]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b6_b7]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b8_b9]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b10_b11]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b12_b13]
set_property IOSTANDARD LVCMOS18 [get_ports Q_b14_b15]
set_property PACKAGE_PIN J11 [get_ports Q_b0_b1]
set_property PACKAGE_PIN K11 [get_ports Q_b2_b3]
set_property PACKAGE_PIN H14 [get_ports Q_b4_b5]
set_property PACKAGE_PIN K13 [get_ports Q_b6_b7]
set_property PACKAGE_PIN J13 [get_ports Q_b8_b9]
set_property PACKAGE_PIN L15 [get_ports Q_b10_b11]
set_property PACKAGE_PIN J15 [get_ports Q_b12_b13]
set_property PACKAGE_PIN L14 [get_ports Q_b14_b15]
set_property PACKAGE_PIN G12 [get_ports SPI0_SS1_O]
set_property PACKAGE_PIN G11 [get_ports SPI0_SS2_O]
set_property PACKAGE_PIN N13 [get_ports SPI0_MOSI_O]

set_property PACKAGE_PIN H11 [get_ports SPI0_SCLK_O]
set_property PACKAGE_PIN H13 [get_ports SPI0_SS_O]
set_property PACKAGE_PIN N14 [get_ports clk_adc]
set_property PACKAGE_PIN M15 [get_ports I_b0_b1]
set_property PACKAGE_PIN R15 [get_ports I_b2_b3]
set_property PACKAGE_PIN R13 [get_ports I_b4_b5]
set_property PACKAGE_PIN L13 [get_ports I_b6_b7]
set_property PACKAGE_PIN R12 [get_ports I_b8_b9]
set_property PACKAGE_PIN M14 [get_ports I_b10_b11]
set_property PACKAGE_PIN L12 [get_ports I_b12_b13]
set_property PACKAGE_PIN P15 [get_ports I_b14_b15]

set_property IOSTANDARD LVCMOS18 [get_ports {gpio_io_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_io_o[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_io_o[3]}]
set_property PACKAGE_PIN J14 [get_ports {gpio_io_o[1]}]
set_property PACKAGE_PIN H12 [get_ports {gpio_io_o[2]}]
set_property PACKAGE_PIN M12 [get_ports {gpio_io_o[3]}]

